
import React, { useState, useEffect } from 'react';
import { fetchDailyRiddle } from '../services/gemini';

interface RiddleRiftProps {
  onGameOver: (score: number) => void;
}

const RiddleRift: React.FC<RiddleRiftProps> = ({ onGameOver }) => {
  const [data, setData] = useState<{ riddle: string; answer: string; hint: string } | null>(null);
  const [guess, setGuess] = useState('');
  const [showHint, setShowHint] = useState(false);
  const [status, setStatus] = useState<'idle' | 'loading' | 'correct' | 'wrong'>('loading');

  useEffect(() => {
    const load = async () => {
      setStatus('loading');
      const res = await fetchDailyRiddle();
      setData(res);
      setStatus('idle');
    };
    load();
  }, []);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!data) return;

    if (guess.toLowerCase().trim() === data.answer.toLowerCase().trim()) {
      setStatus('correct');
      setTimeout(() => onGameOver(1000), 2000);
    } else {
      setStatus('wrong');
      setTimeout(() => setStatus('idle'), 1500);
    }
  };

  if (status === 'loading') {
    return (
      <div className="flex flex-col items-center gap-4">
        <div className="w-16 h-16 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
        <p className="text-indigo-400 font-bold animate-pulse">Summoning Riddle...</p>
      </div>
    );
  }

  return (
    <div className="w-full max-w-md p-8 glass-card rounded-[3rem] border-amber-500/30">
      <div className="text-center mb-8">
        <span className="bg-amber-500/20 text-amber-400 px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-4 inline-block">Daily Challenge</span>
        <h2 className="text-2xl font-bold mb-6 text-white leading-relaxed">"{data?.riddle}"</h2>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <input 
          type="text"
          value={guess}
          onChange={e => setGuess(e.target.value)}
          placeholder="Type your answer..."
          className="w-full bg-white/5 border border-white/10 rounded-2xl px-6 py-4 text-white focus:outline-none focus:ring-2 focus:ring-amber-500 transition-all text-center text-lg"
          autoFocus
        />
        
        <div className="flex gap-3">
          <button 
            type="button"
            onClick={() => setShowHint(true)}
            className="flex-1 py-4 bg-white/10 hover:bg-white/20 rounded-2xl font-bold text-slate-300 transition-all"
          >
            {showHint ? data?.hint : 'Need a Hint?'}
          </button>
          <button 
            type="submit"
            className={`flex-1 py-4 rounded-2xl font-bold text-white transition-all shadow-lg ${
              status === 'correct' ? 'bg-green-500 shadow-green-500/20' : 
              status === 'wrong' ? 'bg-red-500 shadow-red-500/20' : 
              'bg-amber-600 shadow-amber-500/20 hover:scale-105 active:scale-95'
            }`}
          >
            {status === 'correct' ? 'SOLVED!' : status === 'wrong' ? 'TRY AGAIN' : 'SUBMIT'}
          </button>
        </div>
      </form>

      <p className="mt-8 text-center text-xs text-slate-500">
        Riddles generated by Gemini AI. <br/> Come back tomorrow for a new Rift!
      </p>
    </div>
  );
};

export default RiddleRift;
